### ISSUE TITLE
 Clone the repo and install following python packages

### ISSUE THREAD

**Issue by Smiteshraghi** [sudiptab2100/PancakeSwapSnippingBot#1]
hi.
while i'm runing "pip install telethon web3 github"
the github package dont install.
but what do you mean by " g = Github("8f4c3ad5f0d87a248a7cae8777c67d28c535e0ca")" in source code of bot.py??
please help me.
thanks

**Comment by wolfec14** [comment]
I can't install it GITHUB

**Comment by sudiptab2100** [comment]
> hi.
> while i'm runing "pip install telethon web3 github"  
> the github package dont install.

That was a mistake. You have to install PyGithub module to use github.
> but what do you mean by " g = Github("8f4c3ad5f0d87a248a7cae8777c67d28c535e0ca")" in source code of bot.py??
> please help me.
> thanks

This is to create a github instance using an access token. Guide to create your own access token : [Docs](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)

**Comment by sudiptab2100** [comment]
> I can't install it GITHUB

@wolfec14 install _**PyGithub**_ module

**Comment by Smiteshraghi** [comment]
HiThank you very mutch.It was very useful.

    On Wednesday, August 4, 2021, 7:50:34 PM GMT+4:30, Sudipta Basak ***@***.***> wrote:  
 
 



hi.
while i'm runing "pip install telethon web3 github"
the github package dont install.


That was a mistake. You have to install PyGithub module to use github.


but what do you mean by " g = Github("8f4c3ad5f0d87a248a7cae8777c67d28c535e0ca")" in source code of bot.py??
please help me.
thanks


This is to create a github instance using an access token. Guide to create your own access token : Docs

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
