### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by jonathanshannaro** [sudiptab2100/PancakeSwapSnippingBot#2]
![error](https://user-images.githubusercontent.com/79353319/129766864-a9b1f83a-3bf3-4e9d-a949-8b35672e7a81.png)

I have followed your document but I have an error.

**Comment by mandud** [comment]
getting same issue

*edited

Apps works after changing token into my own tokens

**Comment by 252furkan** [comment]
> getting same issue
> 
> *edited
> 
> Apps works after changing token into my own tokens

hi which file you edited ? Thanks

**Comment by jonathanshannaro** [comment]
> getting same issue
> 
> *edited
> 
> Apps works after changing token into my own tokens

**Comment by jonathanshannaro** [comment]
> getting same issue
> 
> *edited
> 
> Apps works after changing token into my own tokens

change the token which you mean? 

Can you say where it is?

**Comment by 252furkan** [comment]
why you closed bro .  i didnt fix it

**Comment by jonathanshannaro** [comment]
> why you closed bro . i didnt fix it

I already know problem bro, g = Github(" ")

use access token, you can take it from your github account settings

**Comment by 252furkan** [comment]
i m trying the bot . it's waiting here. what should  i do ? Thanks 
![image](https://user-images.githubusercontent.com/8388554/129939570-c35e0e59-01ac-408f-a018-b16d3784722c.png)

**Comment by jonathanshannaro** [comment]
> i m trying the bot . it's waiting here. what should i do ? Thanks
> ![image](https://user-images.githubusercontent.com/8388554/129939570-c35e0e59-01ac-408f-a018-b16d3784722c.png)

config.py, make sure you enter provider_url

config.json, fill in all, make sure there are no spaces

bot.py  g = Github("fill in personal token account from GitHub")

**Comment by 252furkan** [comment]
i edited all .  i entered my phone number etc . but still waiting there :(

**Comment by 252furkan** [comment]
![image](https://user-images.githubusercontent.com/8388554/129962085-51abbc86-12c8-43cc-abad-a9d3baa2716b.png)
waiting here :/
